# .github/workflows/build.yml
name: Build & Publish Artifacts

permissions:
  contents: write    # to upload assets to the Release

on:
  release:
    types:
      - created
      - prereleased
      - published

jobs:
  build:
    name: Build & Upload Tauri Bundles
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm v10
        run: npm install -g pnpm@10

      - name: (Debug) Show pnpm path & version
        run: |
          which pnpm
          pnpm --version

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build Tauri bundle
        if: ${{ ! contains(github.event.release.tag_name, '-beta') }}
        run: pnpm exec tauri build

      - name: Upload Bundles to Release
        if: ${{ ! contains(github.event.release.tag_name, '-beta') }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: src-tauri/target/release/bundle/*
          token:     ${{ secrets.RELEASE_TOKEN }}
          prerelease: ${{ github.event.release.prerelease }}
