# GitHub Actions CI for Tauri + pnpm + semantic-release
# Validates on every push/PR; releases on dev/release/*/main; builds on tag; publishes artifacts.

name: CI Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    name: Validate (lint & test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install

  release:
    name: Release (semantic-release)
    needs: validate
    if: |
      github.event_name == 'push' && (
        github.ref == 'refs/heads/dev' ||
        startsWith(github.ref, 'refs/heads/release/') ||
        github.ref == 'refs/heads/main'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        run: pnpm exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build:
    name: Build Artifacts
    needs: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Tauri bundle
        run: pnpm exec tauri build

      - name: Publish Release and Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: src-tauri/target/release/bundle/*
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ contains(github.ref_name, '-rc') }}
